Do not use the new python formatting system
The python3 version in ToolForge doesn't support it yet and it fails
with
  File "/data/project/phabbot/phabbot/new_wikis_handler.py", line 211
    if f"'{language_code}'" in pywikibot:
                          ^
SyntaxError: invalid syntax